apiVersion: v1
kind: ReplicationController

metadata:
  name: mainsitetest-rc

spec:
  replicas: 1
  selector:
    app: mainsitetest

  template:
    metadata:
      name: mainsitetest-pod
      labels:
        app: mainsitetest

    spec:
      containers:
      - name: mainsitetest
        image: gcr.io/voltaic-plating-325610/mainsitetest:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
