apiVersion: v1
kind: ReplicationController

metadata:
  name: jupyternb-rc

spec:
  replicas: 1
  selector:
    app: jupyternb

  template:
    metadata:
      name: jupyternb-pod
      labels:
        app: jupyternb

    spec:
      containers:
      - name: jupyternb
        image: gcr.io/voltaic-plating-325610/jupyternb:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
